### PR TITLE
12.0 [1847][ADD] purchase_report_custom_hls

### PR DESCRIPTION
**Pull request by TomohiroAbe-Quartile**
Staging:
#150 #152 #154 #156 #159 #162 

[1847](https://www.quartile.co/web#view_type=form&model=project.task&id=1847&active_id=1847&menu_id=)

### CODE REVIEW

**Comment by yostashiro** [comment]
@TomohiroAbe-Quartile I think this one https://github.com/qrtl/hls-custom/pull/152 should also be included. Can you check?

**Comment by TomohiroAbe-Quartile** [comment]
@yostashiro 

>  I think this one #152 should also be included. Can you check?
You are right, now picked #152 merge commit.

**Comment by yostashiro** [comment]
@TomohiroAbe-Quartile Travis is failing due to missing purchase_order_secondary_unit, which seems to have left unattended after we put it in the st1 branch of hls-oca.  Can you please follow up on this.  I have revived the task [940](https://www.quartile.co/web?debug=1#id=940&action=771&model=project.task&view_type=form&menu_id=505) and assigned it to you.

**Comment by TomohiroAbe-Quartile** [comment]
@yostashiro 
I made PR on hls-oca branch.
https://github.com/qrtl/hls-oca/pull/13

**Comment by yostashiro** [comment]
> @yostashiro I made PR on hls-oca branch. [qrtl/hls-oca#13](https://github.com/qrtl/hls-oca/pull/13)

Thanks. Please re-run Travis once the hls-oca PR is merged.

**Review by yostashiro — APPROVED** [review]
👍

**Pull request merged**
