### PR TITLE
[1385][IMP]add client order ref on invoice

### PR DESCRIPTION
**Pull request by Ryoko04**
Task [1385](https://www.quartile.co/web#id=1385&action=771&model=project.task&view_type=form&menu_id=505)

added client order ref on invoice_delivery.odt .

invoice layout
(image removed)

libreoffice invoice_delivery.odt file
image

HyperLink setting
  URL:  py3o://function="format_multiline(rl.invoice_line_id.client_order_ref)"
  text：function="format_multiline(rl.invoice_line_id.client_order_ref)"

### CODE REVIEW

**Review by yostashiro — CHANGES_REQUESTED** [review]
@Ryoko04 Can you please make the content of the added column align center (instead of right)?

Also, it may not affect the print result, but I wasn't very comfortable that the line table width has shrunk.

Before this PR:
image

After this PR:
image

**Comment by Ryoko04** [comment]
@yostashiro Thanks a lot for your advices. I will pay attention to them.

**Review by yostashiro — CHANGES_REQUESTED** [review]
@Ryoko04 Please reset the view mode back to 'Web'.
image

Please see https://qrtl.slab.com/posts/py-3-o-tips-error-patterns-694pdoni#py-3-o-template-main-template-exception-every-py-3-o-link-instruction-should-be-on-its-own-line-two-py-3-o-link-instructions-are-on-the-same-line if you haven't.

I'm also a bit concerned about the width of quantity/price/amount fields as they appear to be a narrower than before.  Please double-check the validity against the real data. I think 商品名 and 納入先 could be narrower instead, if anything.

**Comment by Ryoko04** [comment]
client order refがブランクでないときに、商品名欄に印字されるように変更しました。
再Reviewお願いします。
image

**Review by yostashiro — COMMENTED** [review]
@Ryoko04 Wouldn't it be better to align 発注番号 left in that case.

Also, I suppose we don't need to use format_multiline() for 発注番号 (just realized). Can you please check?

**Review by yostashiro — APPROVED** [review]
LGTM 👍

**Pull request merged**
